//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Prod_ID { get; set; }
        public string Prod_Name { get; set; }
        public string Prod_Type { get; set; }
        public double Prod_Price { get; set; }
        public string Prod_Description { get; set; }
    }
}
